### ISSUE TITLE
Using LDSCORE for S-LDSC ?

### ISSUE THREAD

**Issue by restuadi311** [thewonlab/H-MAGMA#4]
Dear H-MAGMA authors,

Thank you very much for providing the LDSCORE data. I'm trying to run S-LDSC using your LDSCORE as the baseline, but it seems not really compatible the available frqfiles (for me it was: **1000G_phase3_frq**)

ldsc.py \
--h2 TRAIT1_2018.sumstats.gz \
--ref-ld-chr ${LDSC_ref}/h_magma_baseline/h_magma_baseline. \
--w-ld-chr ${LDSC_ref}/eur_w_ld_chr/ \
--overlap-annot \
**--frqfile-chr ${LDSC_ref}/1000G_Phase3_frq/1000G.EUR.QC.chr. \**
--print-coefficients \
--out TRAIT1_2018_hMAGMA_tau 

**its always give me these errors (quite likely annot-files incompatible with the frqfiles)** 

Reading annot matrix from /shares/compbio/PCTG/restu/ref/ldsc/h_magma_baseline/h_magma_baseline.[1-22] ...
Error parsing annot matrix.
Error parsing .annot file.
Traceback (most recent call last):
  File "/opt/Modules/ldsc/1.0.0/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/opt/Modules/ldsc/1.0.0/ldscore/sumstats.py", line 369, in estimate_h2
    overlap_matrix, M_tot = _read_annot(args, log)
  File "/opt/Modules/ldsc/1.0.0/ldscore/sumstats.py", line 96, in _read_annot
    'annot matrix', ps.annot, frqfile=args.frqfile_chr)
  File "/opt/Modules/ldsc/1.0.0/ldscore/sumstats.py", line 155, in _read_chr_split_files
    raise e
ValueError: operands could not be broadcast together with shapes (254,254) (2,2) 

Analysis finished at Thu Jul 23 11:58:37 2020

Can you help us by providing the frqfiles or help us to specify frqfiles to use... 

I guess, you were also run S-LDSC on H-MAGMA publication, right?

Thank you very much,

Restu

**Comment by hyejungwon** [comment]
Hi Restu, 

Sorry for the late response. This could be due to two issues. 

1. Sometimes lowering pandas version helps. 
2. S-LDSC file compatibility can be another issue. Seems like some of the files are different from what we used (see below). Please consider re-downloading from https://github.com/bulik/ldsc.
--ref-ld-chr ${LDSC_ref}/h_magma_baseline/h_magma_baseline.
--w-ld-chr ${LDSC_ref}/weights_hm3_no_hla/weights.
--ref-ld-chr ${LDSC_ref}/baselineLD_v1.1/baselineLD.
--frqfile-chr ${LDSC_ref}/1000G_Phase3_frq/1000G.EUR.QC.chr.
